---
- name: create jenkins directory
  file:
    path: ~/jenkins
    state: directory

- name: create jenkins directory tree
  file:
    path: ~/jenkins/{{ item.path }}
    state: directory
  with_filetree: files/
  when: item.state == 'directory'

- name: copy jenkins files
  copy:
    src: "{{ item.src }}"
    dest: ~/jenkins/{{ item.path }}
    mode: preserve
  with_filetree: files/
  when: item.state == 'file'

- name: create kubeconfig
  copy:
    content: "{{ hostvars['localhost'].k8_config }}"
    dest: "~/jenkins/kubeconfig.yml"

- name: build jenkins image
  community.docker.docker_image:
    name: whanos-jenkins
    build:
      path: ~/jenkins
    source: build
    state: present

# - name: print k8 config
#   debug:
#     var: hostvars['localhost'].k8_config

- name: deploy jenkins
  community.docker.docker_compose:
    project_src: ~/jenkins
    # restarted: true
    state: present
  environment:
    JENKINS_ADMIN_USER: "{{ jenkins_admin_user }}"
    JENKINS_ADMIN_PASS: "{{ jenkins_admin_pass }}"
    JENKINS_FULL_DOMAIN: "{{ jenkins_domain }}.{{ domain }}"
    # JENKINS_FULL_DOMAIN: "{{ groups['jenkins'][0] }}:80"

- name: jenkins
  debug:
    msg: "Jenkins OK"