---
- name: don't terraform if the variables file doesn't exists
  meta: end_host
  when: not lookup('fileglob', '../../../terraform/terraform.tfvars')

- name: create instances
  terraform:
    project_path: "../terraform"
    state: present
    force_init: true
    variables:
      domain: "{{ domain }}"
      jenkins_domain: "{{ jenkins_domain }}"
      registry_domain: "{{ registry_domain }}"
  register: infra

# - name: show infrastructure shape
#   debug:
#     var: "infra"

- name: add jenkins ip to group
  add_host:
    name: "{{ infra.outputs.jenkins.value.ipv4_address }}"
    groups: "jenkins"
    ansible_user: root
  changed_when: infra.changed

- name: add registry ip to group
  add_host:
    name: "{{ infra.outputs.registry.value.ipv4_address }}"
    groups: "registry"
    ansible_user: root
  changed_when: infra.changed

- name: register k8 config
  set_fact:
    k8_config: "{{ infra.outputs.k8.value.kube_config[0].raw_config }}"
  changed_when: infra.changed

- name: wait for the droplets to be live
  wait_for:
    port: 22
    host: "{{ item }}"
  with_items:
    - "{{ groups['jenkins'] }}"
    - "{{ groups['registry'] }}"