---
- name: create instances
  terraform:
    project_path: "../terraform"
    state: present
    force_init: true
    variables:
      domain: "{{ domain }}"
      jenkins_domain: "{{ jenkins_domain }}"
  register: infra

# - name: show infrastructure shape
#   debug:
#     var: "infra"

# TODO : Write IPs to host.txt file so we don't get marked as "changed"
# Prob better done in Terraform
- name: add jenkins ips to group
  add_host:
    name: "{{ infra.outputs.jenkins.value.ipv4_address }}"
    groups: "jenkins"
    ansible_user: root

- name: wait for the droplets to be live
  wait_for:
    port: 22
    host: "{{ item }}"
  with_items:
    - "{{ groups['jenkins'] }}"