---
- name: disable unattended updates
  systemd:
    state: stopped
    enabled: false
    daemon_reload: true
    name: unattended-upgrades

- name: install required packages
  apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: true
  # https://github.com/ansible/ansible/issues/51663
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: install required python packages
  pip:
    name: "{{ item }}"
  loop:
    - passlib