version: "3"

# https://docs.docker.com/registry/deploying/

volumes:
  caddy_data:
  registry_data:

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy: "${REGISTRY_FULL_DOMAIN:-localhost:80}"
      caddy.basicauth: "* bcrypt"
      caddy.basicauth.registry: "${REGISTRY_HASHED_PASS:-JDJ5JDEwJFZ4TlpxNkRuZWNnU1pPRXZUeHkyM2U3R0hPbnQ2OUFlY01ZQll4OWVUam9pWlQyOEdmQ055Cg==}"
      # For now registry user is hardcoded to "registry"
      # Default password is "registry"
      # https://github.com/lucaslorentz/caddy-docker-proxy/issues/466
      # caddy.import: "basic_auth ${REGISTRY_USER_NAME:-registry}"
      # caddy_0: "(basic_auth)"
      # caddy_0.basicauth: "* bcrypt"
      # caddy_0.basicauth.{args.0}: "${REGISTRY_HASHED_PASS:-JDJ5JDEwJFZ4TlpxNkRuZWNnU1pPRXZUeHkyM2U3R0hPbnQ2OUFlY01ZQll4OWVUam9pWlQyOEdmQ055Cg==}"

  registry:
    image: registry:latest
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry_data:/var/lib/registry
    labels:
      caddy: "${REGISTRY_FULL_DOMAIN:-localhost:80}"
      caddy.@docker_match.header: "User-Agent *docker*"
      caddy.reverse_proxy: "@docker_match registry:5000"

  web:
    image: parabuzzle/craneoperator:latest
    restart: unless-stopped
    environment:
      REGISTRY_HOST: registry
      REGISTRY_PORT: 5000
      REGISTRY_PROTOCOL: http
      SSL_VERIFY: "false"
      REGISTRY_ALLOW_DELETE: "true"
      REGISTRY_PUBLIC_URL: "${REGISTRY_FULL_DOMAIN:-localhost:80}"
    depends_on:
      - registry
    labels:
      caddy: "${REGISTRY_FULL_DOMAIN:-localhost:80}"
      caddy.reverse_proxy: "web:80"