version: "3"

volumes:
  caddy_data:
  jenkins_data:

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    environment:
      JENKINS_ADMIN_USER: "${JENKINS_ADMIN_USER}"
      JENKINS_ADMIN_PASS: "${JENKINS_ADMIN_PASS}"
    volumes:
      - jenkins_data:/certs/client
      - jenkins_data:/var/jenkins_home
      - jenkins_data:/var/lib/jenkins
      - ~/jenkins/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml:ro
      - ~/jenkins/job_dsl.groovy:/var/jenkins_home/job_dsl.groovy:ro
    labels:
      caddy: "${JENKINS_FULL_DOMAIN}"
      caddy.reverse_proxy: "jenkins:8080"